# Generated by Django 3.0 on 2020-09-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cID', models.CharField(max_length=5)),
                ('cName', models.CharField(max_length=64)),
                ('cTerm', models.PositiveIntegerField()),
                ('cYear', models.CharField(max_length=4)),
                ('avaiable_seat', models.PositiveIntegerField(default=3)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sName', models.CharField(max_length=64)),
                ('sID', models.CharField(max_length=10)),
                ('sClass', models.ManyToManyField(to='regis.Course')),
            ],
        ),
    ]
