# Generated by Django 3.0 on 2020-09-06 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sClass',
        ),
        migrations.AddField(
            model_name='student',
            name='sClass',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='regis.Course'),
            preserve_default=False,
        ),
    ]
