# Generated by Django 3.0 on 2020-09-06 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0002_auto_20200906_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sClass',
        ),
        migrations.AddField(
            model_name='course',
            name='stud',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='regis.Student'),
            preserve_default=False,
        ),
    ]
