# Generated by Django 3.0 on 2020-09-06 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0003_auto_20200906_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='stud',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='regis.Student'),
        ),
    ]
