# Generated by Django 3.0 on 2020-09-06 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0005_remove_course_stud'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sEnroll',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='regis.Course'),
            preserve_default=False,
        ),
    ]
