# Generated by Django 3.0 on 2020-09-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0006_student_senroll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sEnroll',
        ),
        migrations.AddField(
            model_name='student',
            name='sEnroll',
            field=models.ManyToManyField(to='regis.Course'),
        ),
    ]
