# Generated by Django 3.0 on 2020-09-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0007_auto_20200906_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sEnroll',
            field=models.ManyToManyField(blank=True, to='regis.Course'),
        ),
    ]
