# Generated by Django 3.0 on 2020-09-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0008_auto_20200906_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sEnroll',
        ),
        migrations.AddField(
            model_name='course',
            name='attendStd',
            field=models.ManyToManyField(blank=True, to='regis.Student'),
        ),
    ]
